In [11]:
import pandas as pd
import json

## 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [12]:
countries = [
    "US", "RU", "JP", "KR", "MX" ,"CA", "DE", "FR", "GB", "IN"
]

frames = []
for country in countries:
    df = pd.read_csv('data/' + country + "videos.csv.zst", encoding="utf-8", encoding_errors="ignore")
    df["country"] = country
    frames.append(df)

all_videos = pd.concat(frames, ignore_index=True)
all_videos.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,US
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",US
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,US
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,US
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,US

## 2. Extract all videos that have no tag.

In [13]:
all_videos['tags'] = all_videos['tags'].apply(lambda tags_string: [] if tags_string == '[none]' else tags_string.split('|'))
all_videos['tags'] = all_videos['tags'].apply(lambda tags: [tag.replace('"','') for tag in tags])

all_videos['tags']

0                                         [SHANtell martin]
1         [last week tonight trump presidency, last week...
2         [racist superman, rudy, mancuso, king, bach, r...
3         [rhett and link, gmm, good mythical morning, r...
4         [ryan, higa, higatv, nigahiga, i dare you, idy...
                                ...
375937    [twinkle vaishnav comedy, twinkle vaishnav, tw...
375938    [flowers serials, actress, malayalam serials, ...
375939    [mazhavil manorama, bhramanam full episode, gt...
375940    [tarang, tarang tv, tarang tv online, tarang t...
375941    [Ee Nagaraniki Emaindi, Ee Nagaraniki Emaindi ...
Name: tags, Length: 375942, dtype: object

In [14]:
# all_videos['tags'] == ['none']

no_tags = all_videos[all_videos['tags'].apply(lambda tags: len(tags) == 0)]
no_tags

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
42,NZFhMSgbKKM,17.14.11,Dennis Smith Jr. and LeBron James go back and ...,Ben Rohrbach,17,2017-11-13T15:11:00.000Z,[],945,7,5,8,https://i.ytimg.com/vi/NZFhMSgbKKM/default.jpg,False,False,False,NaN,US
97,xfmipNU4Odc,17.14.11,Edna's registered owner thought she was dead f...,Hope For Paws - Official Rescue Channel,15,2017-11-10T18:02:04.000Z,[],284666,16396,81,949,https://i.ytimg.com/vi/xfmipNU4Odc/default.jpg,False,False,False,Please donate $5 and help us save more lives:\...,US
133,X7flefV8tec,17.14.11,"President Bill Clinton On Dictators, Democracy...",Team Coco,24,2017-11-09T02:37:49.000Z,[],366180,4364,4448,1997,https://i.ytimg.com/vi/X7flefV8tec/default.jpg,False,False,False,#ConanNYC Highlight: President Clinton talks a...,US
136,5x1FAiIq_pQ,17.14.11,Alicia Keys - When You Were Gone,Alicia Keys,10,2017-11-09T15:49:21.000Z,[],95944,1354,181,117,https://i.ytimg.com/vi/5x1FAiIq_pQ/default.jpg,False,False,False,Find out more in The Vault: http://bit.ly/AK_A...,US
175,4d07RXYLsJE,17.14.11,Sphaera - demonstrating interaction,Jenny Hanell,28,2017-11-04T20:48:16.000Z,[],1827,3,0,2,https://i.ytimg.com/vi/4d07RXYLsJE/default.jpg,False,False,False,NaN,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375543,79GMkkOzP3Q,18.12.06,മഞ്ജുവിനെ ആശ്വസിപ്പിക്കാൻ ദിലീപ് മീനാക്ഷിക്കൊപ...,Entertainment Journalist,24,2018-06-10T18:21:38.000Z,[],102191,80,54,8,https://i.ytimg.com/vi/79GMkkOzP3Q/default.jpg,False,False,False,മഞ്ജുവിനെ ആശ്വസിപ്പിക്കാൻ ദിലീപ് മീനാക്ഷിക്കൊപ...,IN
375658,IkScPfdGRmk,18.13.06,RABB JANE (Full Video) Afsana Khan ft Garry Sa...,Fresh Media Records,10,2018-06-12T04:19:27.000Z,[],607257,13400,512,1031,https://i.ytimg.com/vi/IkScPfdGRmk/default.jpg,False,False,False,LISTEN ON https://gaana.com/song/rabb-jane-unp...,IN
375700,SAQLDbFGypU,18.13.06,my FaVoriTE CELL PhonEs! (tech tuesday intro b...,CaseyNeistat,22,2018-06-12T15:23:28.000Z,[],753230,32170,667,3831,https://i.ytimg.com/vi/SAQLDbFGypU/default.jpg,False,False,False,follow me on Twitter - https://twitter.com/Cas...,IN
375814,8aMckaI9k00,18.14.06,Indore Preview- Chacha Vidhayak Hai Humare - Z...,Zakir Khan,22,2018-06-13T14:18:31.000Z,[],274861,16448,183,834,https://i.ytimg.com/vi/8aMckaI9k00/default.jpg,False,False,False,"Suno, Sab sort karva denge. Chacha vidhayak ha...",IN
375936,8aMckaI9k00,18.14.06,Indore Preview- Chacha Vidhayak Hai Humare - Z...,Zakir Khan,22,2018-06-13T14:18:31.000Z,[],274861,16448,183,834,https://i.ytimg.com/vi/8aMckaI9k00/default.jpg,False,False,False,"Suno, Sab sort karva denge. Chacha vidhayak ha...",IN

## 3. For each channel, determine the total number of views

In [15]:
all_videos[all_videos['video_id'] == 'n1WpP7iowLc']

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
32,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158531,787419,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,US
298,n1WpP7iowLc,17.15.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",20539417,840642,47715,124236,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,US
534,n1WpP7iowLc,17.16.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",22702386,869304,50018,123227,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,US
766,n1WpP7iowLc,17.17.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",24578152,891282,51977,125444,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,US
995,n1WpP7iowLc,17.18.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",26448434,911883,53873,127481,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,US
102369,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787426,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,KR
177229,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
177443,n1WpP7iowLc,17.15.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",20539417,840642,47715,124236,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
177727,n1WpP7iowLc,17.16.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",22702386,869304,50018,123235,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
178020,n1WpP7iowLc,17.17.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",24578152,891283,51978,125444,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
218146,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787424,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,DE
259020,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,FR
299676,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
299893,n1WpP7iowLc,17.15.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",20539417,840642,47715,124236,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
300101,n1WpP7iowLc,17.16.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",22702386,869304,50018,123227,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
300340,n1WpP7iowLc,17.17.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",24578152,891283,51977,125444,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
300550,n1WpP7iowLc,17.18.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",26448434,911883,53873,127481,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
300765,n1WpP7iowLc,17.19.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",28484854,935289,55701,128692,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
300970,n1WpP7iowLc,17.20.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",30395840,960591,57370,130561,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
301187,n1WpP7iowLc,17.21.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",32109264,978775,58824,131495,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
301394,n1WpP7iowLc,17.22.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",33716279,994089,60095,132816,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
301629,n1WpP7iowLc,17.23.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",35228945,1008477,61194,134163,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
301839,n1WpP7iowLc,17.24.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",36267497,1018472,61880,135031,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
302048,n1WpP7iowLc,17.25.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",37301803,1027441,62561,135983,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
302253,n1WpP7iowLc,17.26.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",38335756,1036476,63195,136573,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB
302456,n1WpP7iowLc,17.27.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",39235314,1044324,63815,137383,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB

### Observation : Duplicate rows exists. its the same video but trended on diffrent countries and dates.

In [16]:
all_videos[(all_videos['video_id'] == 'n1WpP7iowLc') & (all_videos['trending_date'] == '17.14.11')]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
32,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158531,787419,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,US
102369,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787426,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,KR
177229,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
218146,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787424,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,DE
259020,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,FR
299676,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB

In [17]:
sorted_df = all_videos.sort_values(by="likes", ascending=True)

unique_df = sorted_df.drop_duplicates(subset="video_id", keep="last")

In [18]:
unique_df[unique_df['video_id'] == 'n1WpP7iowLc']

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
302456,n1WpP7iowLc,17.27.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"[Eminem, Walk, On, Water, Aftermath/Shady/Inte...",39235314,1044324,63815,137383,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,GB

In [19]:
# For each channel, determine the total number of views
channel_views = unique_df.groupby('channel_title')['views'].sum()

# convert data series to data frame and add index column
channel_views = channel_views.reset_index()

channel_views.sort_values('views', ascending=False)

           channel_title      views
22986           T-Series  549514687
18373              Ozuna  496503490
17634         NickyJamTV  467892045
6657           DrakeVEVO  364312023
2770           Bad Bunny  357112379
...                  ...        ...
17346  NavylittleMonster        365
25696   Videostendencias        302
17745      No Comment TV        284
22443         Sport Life        163
1363   Alexander Redking        153

[37580 rows x 2 columns]

## 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [20]:
mask = (
    (unique_df['comments_disabled'] == True) &
    (unique_df['ratings_disabled'] == True) |
    (unique_df['video_error_or_removed'] == True)
)

# just in case we need the original dataset later
org_df = unique_df.copy()

excluded = unique_df[mask]
unique_df = unique_df[~mask]
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
254265,V310P6wE_Lw,18.22.05,Yeni Evlenen Kadının Başına Bakın Ne Geldi Ama...,Son 24 Saat,25,2018-05-21T09:00:03.000Z,"[Evli, Yeni Evli, Gelin, Damat, Kayınpeder, An...",414874,0,0,0,https://i.ytimg.com/vi/V310P6wE_Lw/default.jpg,True,True,False,"Kadın yeni evli, başına gelen olay akıl alır g...",DE
89162,s5YsvbkMU4Q,18.23.03,とんねるず 最後の挨拶～最終回 エンディング 2018年3月22日の番組,まとめ,22,2018-03-22T13:54:21.000Z,[],33614,0,0,0,https://i.ytimg.com/vi/s5YsvbkMU4Q/default.jpg,True,True,False,【豪華特典付き】インターネットで稼げるようになった秘密の暴露マンガが今なら無料で読めます。\...,JP
288308,J7wVRBsFpqc,18.18.04,Tomahawk Racing le parcours en vrac,Tomahawktuning,2,2018-04-17T14:58:35.000Z,[],3697,0,0,0,https://i.ytimg.com/vi/J7wVRBsFpqc/default.jpg,True,True,False,NaN,FR
271882,7y-D4Ru6ibU,18.19.01,8 Façons d'Avoir Une Grande VIE,Franck Nicolas,26,2018-01-18T18:56:57.000Z,"[glob, franck, nicolas, conférencier, conferen...",6137,0,0,0,https://i.ytimg.com/vi/7y-D4Ru6ibU/default.jpg,True,True,False,NaN,FR
275461,2GekURmjcIA,18.06.02,Gilad Atzmon interrogé par la télévision turqu...,ERTV Officiel,25,2018-02-05T10:24:52.000Z,"[Atzmon, Turquie, Israël, Trump]",9054,0,0,0,https://i.ytimg.com/vi/2GekURmjcIA/default.jpg,True,True,False,Une traduction E&R.\n\nPour commenter cette vi...,FR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125744,RmZ3DPJQo2k,18.05.04,Ep3 Just give me a smile | BTS: Burn the Stage,BANGTANTV,10,2018-04-04T15:00:05.000Z,"[방탄소년단, 슈가, 지민, 랩몬스터, 진, 정국, 제이홉, 뷔, 빅히트, 방탄, ...",3086615,340359,5666,34030,https://i.ytimg.com/vi/RmZ3DPJQo2k/default.jpg,False,False,True,"In their most private moment, BTS open up and ...",KR
189240,7qmSwj8Pwys,18.15.01,Deleted video,PewDiePie,23,2018-01-13T18:46:44.000Z,"[pewdiepie, mad lad]",3954942,344105,7173,31539,https://i.ytimg.com/vi/RkvczNWh9ZM/default.jpg,False,False,True,|AD| Shop and save on the HONOR 7X Lucky Bag p...,CA
250452,BEePFpC9qG8,18.03.05,360 Google Doodles/Spotlight Stories: Back to ...,Google Spotlight Stories,1,2018-05-02T13:42:03.000Z,"[google spotlight stories, spotlight stories, ...",12498037,373875,6350,27599,https://i.ytimg.com/vi/BEePFpC9qG8/default.jpg,False,False,True,"The Google Doodle, Google Spotlight Stories, G...",DE
366413,q8v9MvManKE,18.23.04,Earth Day 2018 Google Doodle,googledoodles,1,2018-04-21T15:00:50.000Z,[],4733057,445947,10306,35394,https://i.ytimg.com/vi/q8v9MvManKE/default.jpg,False,False,True,Today’s annual Earth Day Doodle was created in...,IN
337401,1Aoc-cd9eYs,18.07.06,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"[Cobra Kai, Karate Kid, YouTube Red Original S...",50122125,873431,119401,85578,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,GB

## 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [21]:
dislikes = unique_df['dislikes'].replace(0, pd.NA)
likes = unique_df['likes'].replace(0, pd.NA)

unique_df['like_ratio'] = likes / dislikes
unique_df[['likes', 'dislikes', 'like_ratio']]

          likes  dislikes like_ratio
89166         0         0       <NA>
89372         0         0       <NA>
348838        0         0       <NA>
89321         0         0       <NA>
89319         0         0       <NA>
...         ...       ...        ...
335394  3394437    150086  22.616613
325219  3823879    215530  17.741748
325610  4737873    117198  40.426227
338075  5444541    379862  14.332945
38273   5613827    206892  27.134094

[182879 rows x 3 columns]

## 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [22]:
publish_dt = pd.to_datetime(unique_df['publish_time'], errors='coerce', utc=True)

# create a series of date times
# convert the date time to the nearest 10 minutes
interval_start = publish_dt.dt.floor('10min')

# add 10 minutes
interval_end = interval_start + pd.Timedelta(minutes=10)

unique_df['publish_interval_10min'] = (
    interval_start.dt.strftime('%H:%M') + ' - ' + interval_end.dt.strftime('%H:%M')
)

unique_df[['publish_time', 'publish_interval_10min']].head()

                    publish_time publish_interval_10min
89166   2018-03-22T12:09:51.000Z          12:00 - 12:10
89372   2018-03-23T15:45:00.000Z          15:40 - 15:50
348838  2018-01-06T08:36:48.000Z          08:30 - 08:40
89321   2018-03-23T11:53:27.000Z          11:50 - 12:00
89319   2018-03-23T11:00:03.000Z          11:00 - 11:10

## 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [23]:
output_df = unique_df.groupby('publish_interval_10min')['video_id'].size().to_frame(name='video_count')

output_df['dislike_avg'] = unique_df.groupby('publish_interval_10min')['dislikes'].mean().round()
output_df['like_avg'] = unique_df.groupby('publish_interval_10min')['likes'].mean().round()

output_df

                        video_count  dislike_avg  like_avg
publish_interval_10min
00:00 - 00:10                  1371       1019.0   12121.0
00:10 - 00:20                   743        431.0    7305.0
00:20 - 00:30                   647        654.0    7969.0
00:30 - 00:40                   835        339.0    7664.0
00:40 - 00:50                   633        491.0    8709.0
...                             ...          ...       ...
23:10 - 23:20                   798        473.0    7569.0
23:20 - 23:30                   713        624.0    9944.0
23:30 - 23:40                   901        410.0    6615.0
23:40 - 23:50                   733       1112.0    9381.0
23:50 - 00:00                   686        388.0    5624.0

[144 rows x 3 columns]

## 8. For each tag, determine the number of videos

In [24]:
all_tags = set()
for tags in df['tags']:
    all_tags.update(tags)


all_tags

{' ',
 '!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 '-',
 '.',
 '/',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '=',
 '?',
 '@',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 '\\',
 ']',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '\xa0',
 '¡',
 '£',
 '\xad',
 '®',
 '²',
 'Ç',
 '×',
 'á',
 'é',
 'í',
 'î',
 'ñ',
 'ó',
 'ö',
 'ú',
 'ü',
 'ć',
 'ş',
 'с',
 'آ',
 'أ',
 'ؤ',
 'إ',
 'ا',
 'ب',
 'ة',
 'ت',
 'ث',
 'ج',
 'ح',
 'خ',
 'د',
 'ذ',
 'ر',
 'ز',
 'س',
 'ش',
 'ص',
 'ط',
 'ع',
 'غ',
 'ـ',
 'ف',
 'ق',
 'ك',
 'ل',
 'م',
 'ن',
 'ه',
 'و',
 'ى',
 'ي',
 'چ',
 'ک',
 'ی',
 'ँ',
 'ं',
 'अ',
 'आ',
 'इ',
 'ई',
 'उ',
 'ऊ',
 'ऋ',
 'ए',
 'ऐ',
 'ऑ',
 'ओ',
 'औ',
 'क',
 'ख',
 'ग',
 'घ',
 'च',
 'छ',
 'ज',
 'झ',
 'ञ',
 'ट',
 'ठ',
 'ड',
 'ढ',
 'ण',
 'त',
 'थ',
 'द',
 'ध',
 'न',
 'प',
 'फ',
 'ब',
 'भ',
 'म',
 'य',
 'र',
 'ऱ',
 'ल',
 'ळ',
 'व',
 'श',
 'ष',
 'स',
 'ह',
 '़',
 'ा',
 'ि',
 'ी',
 'ु',
 'ू',
 'ृ',
 'ॅ',
 'े',
 'ै',
 'ॉ',
 'ो',
 'ौ',
 '्',
 'ॐ',
 'ख़',
 'ग़',
 'ज़',
 'ड़',
 'ढ़',
 'फ़',
 '।',
 '०',
 '१',
 '२',
 '३',
 '४',
 '५',
 '७',
 'ং',
 'অ',
 'আ',
 'ই',
 'উ',
 'এ',
 'ও',
 'ক',
 'খ',
 'গ',
 'ঘ',
 'ঙ',
 'চ',
 'ছ',
 'জ',
 'ঞ',
 'ট',
 'ঠ',
 'ড',
 'ণ',
 'ত',
 'থ',
 'দ',
 'ধ',
 'ন',
 'প',
 'ফ',
 'ব',
 'ভ',
 'ম',
 'য',
 'র',
 'ল',
 'শ',
 'ষ',
 'স',
 'হ',
 '়',
 'া',
 'ি',
 'ী',
 'ু',
 'ৃ',
 'ে',
 'ৈ',
 'ো',
 'ৌ',
 '্',
 'ৎ',
 'ড়',
 'য়',
 '১',
 '৫',
 'ਂ',
 'ਅ',
 'ਆ',
 'ਇ',
 'ਈ',
 'ਊ',
 'ਐ',
 'ਓ',
 'ਕ',
 'ਖ',
 'ਗ',
 'ਘ',
 'ਚ',
 'ਜ',
 'ਟ',
 'ਡ',
 'ਢ',
 'ਣ',
 'ਤ',
 'ਥ',
 'ਦ',
 'ਧ',
 'ਨ',
 'ਪ',
 'ਫ',
 'ਬ',
 'ਭ',
 'ਮ',
 'ਯ',
 'ਰ',
 'ਲ',
 'ਵ',
 'ਸ਼',
 'ਸ',
 'ਹ',
 'ਾ',
 'ਿ',
 'ੀ',
 'ੁ',
 'ੂ',
 'ੇ',
 'ੈ',
 'ੋ',
 'ੌ',
 '੍',
 'ੜ',
 'ਫ਼',
 'ੰ',
 'ੱ',
 'ં',
 'અ',
 'આ',
 'ઇ',
 'ઈ',
 'ઉ',
 'એ',
 'ઓ',
 'ક',
 'ખ',
 'ગ',
 'ઘ',
 'ચ',
 'છ',
 'જ',
 'ઝ',
 'ટ',
 'ઠ',
 'ડ',
 'ઢ',
 'ણ',
 'ત',
 'થ',
 'દ',
 'ધ',
 'ન',
 'પ',
 'ફ',
 'બ',
 'ભ',
 'મ',
 'ય',
 'ર',
 'લ',
 'ળ',
 'વ',
 'શ',
 'ષ',
 'સ',
 'હ',
 'ા',
 'િ',
 'ી',
 'ુ',
 'ૂ',
 'ે',
 'ૉ',
 'ો',
 '્',
 'ஃ',
 'அ',
 'ஆ',
 'இ',
 'ஈ',
 'உ',
 'எ',
 'ஏ',
 'ஐ',
 'ஒ',
 'ஓ',
 'க',
 'ங',
 'ச',
 'ஜ',
 'ஞ',
 'ட',
 'ண',
 'த',
 'ந',
 'ன',
 'ப',
 'ம',
 'ய',
 'ர',
 'ற',
 'ல',
 'ள',
 'ழ',
 'வ',
 'ஷ',
 'ஸ',
 'ஹ',
 'ா',
 'ி',
 'ீ',
 'ு',
 'ூ',
 'ெ',
 'ே',
 'ை',
 'ொ',
 'ோ',
 '்',
 'ఁ',
 'ం',
 'ః',
 'అ',
 'ఆ',
 'ఇ',
 'ఈ',
 'ఉ',
 'ఊ',
 'ఎ',
 'ఏ',
 'ఐ',
 'ఒ',
 'ఓ',
 'క',
 'ఖ',
 'గ',
 'ఘ',
 'చ',
 'ఛ',
 'జ',
 'ఞ',
 'ట',
 'ఠ',
 'డ',
 'ఢ',
 'ణ',
 'త',
 'థ',
 'ద',
 'ధ',
 'న',
 'ప',
 'ఫ',
 'బ',
 'భ',
 'మ',
 'య',
 'ర',
 'ల',
 'ళ',
 'వ',
 'శ',
 'ష',
 'స',
 'హ',
 'ా',
 'ి',
 'ీ',
 'ు',
 'ూ',
 'ృ',
 'ె',
 'ే',
 'ై',
 'ొ',
 'ో',
 'ౌ',
 '్',
 'ౖ',
 'ಂ',
 'ಅ',
 'ಆ',
 'ಇ',
 'ಈ',
 'ಉ',
 'ಎ',
 'ಏ',
 'ಐ',
 'ಒ',
 'ಔ',
 'ಕ',
 'ಖ',
 'ಗ',
 'ಘ',
 'ಚ',
 'ಜ',
 'ಟ',
 'ಡ',
 'ಢ',
 'ಣ',
 'ತ',
 'ಥ',
 'ದ',
 'ಧ',
 'ನ',
 'ಪ',
 'ಫ',
 'ಬ',
 'ಭ',
 'ಮ',
 'ಯ',
 'ರ',
 'ಲ',
 'ಳ',
 'ವ',
 'ಶ',
 'ಷ',
 'ಸ',
 'ಹ',
 'ಾ',
 'ಿ',
 'ೀ',
 'ು',
 'ೂ',
 'ೃ',
 'ೆ',
 'ೇ',
 'ೈ',
 'ೊ',
 'ೋ',
 'ೌ',
 '್',
 'ം',
 'അ',
 'ആ',
 'ഇ',
 'ഈ',
 'ഉ',
 'എ',
 'ഏ',
 'ഐ',
 'ഒ',
 'ഓ',
 'ക',
 'ഖ',
 'ഗ',
 'ങ',
 'ച',
 'ഛ',
 'ജ',
 'ഞ',
 'ട',
 'ഡ',
 'ണ',
 'ത',
 'ഥ',
 'ദ',
 'ധ',
 'ന',
 'പ',
 'ഫ',
 'ബ',
 'ഭ',
 'മ',
 'യ',
 'ര',
 'റ',
 'ല',
 'ള',
 'ഴ',
 'വ',
 'ശ',
 'ഷ',
 'സ',
 'ഹ',
 'ാ',
 'ി',
 'ീ',
 'ു',
 'ൂ',
 'ൃ',
 'െ',
 'േ',
 'ൈ',
 'ൊ',
 'ോ',
 '്',
 'ൗ',
 'ൺ',
 'ൻ',
 'ർ',
 'ൽ',
 'ൾ',
 'ạ',
 '\u200b',
 '\u200c',
 '\u200d',
 '\u200e',
 '–',
 '‘',
 '’',
 '“',
 '”',
 '†',
 '…',
 '\u202a',
 '\u202c',
 '™',
 '●',
 '✔',
 '担',
 '面',
 '️',
 '🍎',
 '💖',
 '😢'}

In [25]:
tag_counts = {}

for tags in unique_df['tags']:
    for tag in tags:
        if tag not in tag_counts:
            tag_counts[tag] = 0

        tag_counts[tag] += 1

tag_counts = pd.Series(tag_counts)
tag_counts

深夜ラジオ                     50
オールナイトニッポン                36
バカリズム                      3
RS Media                  17
RamSar Media              17
                          ..
April the Giraffe          1
Drake new music            1
Drake God’s Plan           1
Drake Charity Giveaway     1
Drake in Miami             1
Length: 843587, dtype: int64

## 9. Find the tags with the largest number of videos

In [26]:
tag_counts.sort_values(ascending=False)

2018                   5743
funny                  4144
comedy                 3102
news                   3048
2017                   2651
                       ...
Natti Natasha Video       1
Dueling Dua Lipas         1
Double Dua Lipas          1
BQ0mxQXmLsk               1
8zSRkr1nQNw               1
Length: 843587, dtype: int64

## 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [35]:
df_tags = unique_df.copy()

df_tags = df_tags.explode('tags')

average_ratios = df_tags.groupby(['country', 'tags'])['like_ratio'].mean()

In [38]:
df_tags.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min,year,month,day
89166,zmISBHbr4ZY,18.23.03,【最終回】バカリズムのオールナイトニッポンPremium 2018年03月22日,radiolife,22,2018-03-22T12:09:51.000Z,深夜ラジオ,4056,0,0,...,False,True,False,NaN,JP,<NA>,12:00 - 12:10,2018,3,23
89166,zmISBHbr4ZY,18.23.03,【最終回】バカリズムのオールナイトニッポンPremium 2018年03月22日,radiolife,22,2018-03-22T12:09:51.000Z,オールナイトニッポン,4056,0,0,...,False,True,False,NaN,JP,<NA>,12:00 - 12:10,2018,3,23
89166,zmISBHbr4ZY,18.23.03,【最終回】バカリズムのオールナイトニッポンPremium 2018年03月22日,radiolife,22,2018-03-22T12:09:51.000Z,バカリズム,4056,0,0,...,False,True,False,NaN,JP,<NA>,12:00 - 12:10,2018,3,23
89372,RP4CggHBO7s,18.24.03,"Bhadragol, 23rd March 2018, Full Episode 164",RamSar Media Pvt. Ltd,24,2018-03-23T15:45:00.000Z,RS Media,334074,0,0,...,False,True,False,Bhadragol is a nepali Tv serial broadcasting e...,JP,<NA>,15:40 - 15:50,2018,3,24
89372,RP4CggHBO7s,18.24.03,"Bhadragol, 23rd March 2018, Full Episode 164",RamSar Media Pvt. Ltd,24,2018-03-23T15:45:00.000Z,RamSar Media,334074,0,0,...,False,True,False,Bhadragol is a nepali Tv serial broadcasting e...,JP,<NA>,15:40 - 15:50,2018,3,24

In [36]:
average_ratios

country  tags
CA                                                7.708077
          'Gandarrappido: The Revenger Squad     20.697017
          100% Will Get Satisfied                 7.034535
          140118 💖                                 3.90184
          150118 💖                                4.123711
                                                   ...
US       황현진                                      53.80335
         회오리젤리                                        57.3
         효정                                      53.250399
         🇰🇵                                          4.875
         🍎                                       43.889834
Name: like_ratio, Length: 958782, dtype: object

## # 11. For each (trending_date, country) pair, the video with the largest number of views

In [28]:
unique_df.loc[unique_df.groupby(['trending_date', 'country'])['views'].idxmax()]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min
180794,TCoZstGksJ8,17.01.12,10 Times The Pawn Stars Got Scammed,Screen Hub,20,2017-11-25T23:26:04.000Z,"[pawn stars, pawn stars full episode, pawn sta...",3765943,19881,6631,1985,https://i.ytimg.com/vi/TCoZstGksJ8/default.jpg,False,False,False,10 Times the Pawn Stars Got Scammed! For more ...,CA,2.99819,23:20 - 23:30
221603,GtrJVIS55U8,17.01.12,Beşiktaş - G. Medical Manisaspor Maç Özeti,a2,22,2017-11-28T14:33:44.000Z,"[ziraat türkiye kupası, ztk, beşiktaş, manisas...",1647801,9786,1772,3691,https://i.ytimg.com/vi/GtrJVIS55U8/default.jpg,False,False,False,Beşiktaş - G. Medical Manisaspor Ziraat Türkiy...,DE,5.522573,14:30 - 14:40
262367,oTAIAE1qiNQ,17.01.12,VOUS AVEZ UN INCROYABLE TALENT !!,Tibo InShape,17,2017-11-28T17:00:30.000Z,"[tibo inshape, talent tibo inshape, vous avez ...",1279340,79145,1695,7032,https://i.ytimg.com/vi/oTAIAE1qiNQ/default.jpg,False,False,False,Mes abonnés ont un incroyable talent ! \nCliqu...,FR,46.693215,17:00 - 17:10
303261,TyHvyGVs42U,17.01.12,"Luis Fonsi, Demi Lovato - Échame La Culpa",LuisFonsiVEVO,10,2017-11-17T05:00:01.000Z,"[Luis, Fonsi, Demi, Lovato, Échame, La, Culpa,...",143408235,2686169,137938,144217,https://i.ytimg.com/vi/TyHvyGVs42U/default.jpg,False,False,False,“Échame La Culpa” disponible ya en todas las p...,GB,19.473742,05:00 - 05:10
341970,hQkQlRYqvtg,17.01.12,Naragasooran - Official Teaser | Arvind Swami ...,Ondraga Entertainment,1,2017-11-25T11:32:48.000Z,"[Ondraga Entertainment, Naragasooran, Naragaso...",1908682,37184,1371,1294,https://i.ytimg.com/vi/hQkQlRYqvtg/default.jpg,False,False,False,"Cast : Arvind Swami, Shriya Saran, Sundeep Kis...",IN,27.121809,11:30 - 11:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99862,N0jfxOKo70U,18.31.05,ミシンでLINEスタンプ高速連打したら友達キレるか？【検証】 PDS,PDSKabushikiGaisha,24,2018-05-30T11:13:36.000Z,"[ダンテ, PDS, ペインダンテ, 株式会社, ジャニーズ, LINE, スタンプ, ドッ...",858759,10081,3095,2071,https://i.ytimg.com/vi/N0jfxOKo70U/default.jpg,False,False,False,PDS LINEスタンプ↓ https://store.line.me/sticker...,JP,3.257189,11:10 - 11:20
134168,XUNWoQ__ekw,18.31.05,"홍준표, 막말 해명하다 오히려 대학생에게 망신 (기자보다 훌륭한 성균관대 학생의 송...",MediaVOP,25,2018-05-28T09:30:09.000Z,"[홍준표, 성균관대, 강연, 대학생, 자유한국당, 빨갱이]",1174957,5115,1474,5061,https://i.ytimg.com/vi/XUNWoQ__ekw/default.jpg,False,False,False,NaN,KR,3.470149,09:30 - 09:40
174467,1Lii8RHdNFo,18.31.05,“NEY no debe ir al MADRID” | BRONCA entre alem...,Cracks,17,2018-05-30T22:55:15.000Z,"[Cracks, UCL, Manu Bravo, Fútbol, Futebol, Soc...",1177032,66357,2144,3024,https://i.ytimg.com/vi/1Lii8RHdNFo/default.jpg,False,False,False,CRACKS COLOMBIA: https://www.youtube.com/chann...,MX,30.950093,22:50 - 23:00
78924,Y0ja0j5EIq8,18.31.05,ШКОЛА И ПЕРВАЯ ЛЮБОВЬ 1 серия ⭐ Премьера!,Barvina,24,2018-05-30T03:30:01.000Z,[],726253,27358,3418,8847,https://i.ytimg.com/vi/Y0ja0j5EIq8/default.jpg,False,False,False,Сериал ШКОЛА и первая любовь 1я серия — Спин-...,RU,8.004096,03:30 - 03:40
38064,2-tzlBFotjA,18.31.05,My Summer Crush | Hannah Stocking,Hannah Stocking,23,2018-05-19T16:30:09.000Z,"[my summer crush, hannah, stocking, my, summer...",4280876,124337,11809,6284,https://i.ytimg.com/vi/2-tzlBFotjA/default.jpg,False,False,False,WATCH MORE ▶ https://youtu.be/_iGAptGAweoSUBSC...,US,10.529003,16:30 - 16:40

## 12. Divide trending_date into three columns: year, month, day

In [29]:
trending_date = pd.to_datetime(unique_df['trending_date'], format='%y.%d.%m', errors='coerce')
unique_df['year'] = trending_date.dt.year
unique_df['month'] = trending_date.dt.month
unique_df['day'] = trending_date.dt.day

unique_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min,year,month,day
89166,zmISBHbr4ZY,18.23.03,【最終回】バカリズムのオールナイトニッポンPremium 2018年03月22日,radiolife,22,2018-03-22T12:09:51.000Z,"[深夜ラジオ, オールナイトニッポン, バカリズム]",4056,0,0,...,False,True,False,NaN,JP,<NA>,12:00 - 12:10,2018,3,23
89372,RP4CggHBO7s,18.24.03,"Bhadragol, 23rd March 2018, Full Episode 164",RamSar Media Pvt. Ltd,24,2018-03-23T15:45:00.000Z,"[RS Media, RamSar Media, Comedy Serial, Bhadra...",334074,0,0,...,False,True,False,Bhadragol is a nepali Tv serial broadcasting e...,JP,<NA>,15:40 - 15:50,2018,3,24
348838,LWbzf4XChuo,18.07.01,Natchathira Vizha 2018 || Captains Mass Entry,Tamil Cini,24,2018-01-06T08:36:48.000Z,"[Natchathira Vizha 2018 , , Captions Mass Ent...",51345,0,0,...,False,True,False,Raja Rani Serial Application Download Below Li...,IN,<NA>,08:30 - 08:40,2018,1,7
89321,mqVvJmsYsms,18.24.03,【乃木坂46 与田祐希】ゲテモノに挑戦する与田ちゃんとドSなあしゅｗ【齋藤飛鳥】,emi lia,24,2018-03-23T11:53:27.000Z,"[乃木坂, 46, 与田, 与田祐希, 与田ちゃん, ゲテモノ, 可愛い, アイドル, 電視台]",94793,0,0,...,False,True,False,可愛いのに挑戦内容とのギャップがすごいｗ,JP,<NA>,11:50 - 12:00,2018,3,24
89319,KCZiHEWPfFU,18.24.03,SixTONESは本当に仲が良いのか？以心伝心ゲームで検証！,ジャニーズJr.チャンネル,24,2018-03-23T11:00:03.000Z,"[ジャニーズJr. チャンネル, ジャニーズ, johnny's, ジャニーズ jr, jo...",163676,0,0,...,False,True,False,YouTubeをご覧の皆さん「SixTONES」です。\n僕たちは、プライベートで全く一緒に...,JP,<NA>,11:00 - 11:10,2018,3,24

## 13. For each (month, country) pair, the video with the largest number of views

In [ ]:
# Year must be take in considiration otherwise it will overlap
unique_df.loc[unique_df.groupby(['year', 'month', 'country'])['views'].idxmax()]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,publish_interval_10min,year,month,day
180226,RSRzIrOqaN4,17.28.11,"Romeo Santos, Daddy Yankee, Nicky Jam - Bella ...",RomeoSantosVEVO,10,2017-11-24T05:00:00.000Z,"[Romeo Santos, Daddy Yankee, & Nicky Jam, & Ni...",17208914,380861,14969,...,False,False,False,"Romeo Santos, Daddy Yankee & Nicky Jam - Bella...",CA,25.443316,05:00 - 05:10,2017,11,28
218571,UhAKwwjn2f8,17.16.11,Söz | 21.Bölüm,Söz Dizi,1,2017-11-14T00:39:50.000Z,"[söz, soz, tims&b, tolga sarıtaş, aybüke pusat...",3221754,32043,2139,...,False,False,False,Türkiye’nin en büyük prodüksiyonlu asker dizis...,DE,14.980365,00:30 - 00:40,2017,11,16
260278,E8B1c3NpLpc,17.20.11,Miss World 2017 - Crowning Moment,Latino Vicente,22,2017-11-18T14:05:29.000Z,"[Miss World 2017, Miss World 2017 Full show, M...",7664480,104444,3865,...,False,False,False,Miss World 2017 - Crowning Moment | Miss World...,FR,27.023027,14:00 - 14:10,2017,11,20
302468,2Vv-BfVoq4g,17.27.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"[edsheeran, ed sheeran, acoustic, live, cover,...",138578860,2584773,49428,...,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,GB,52.2937,11:00 - 11:10,2017,11,27
341635,xmU0s2QtaEY,17.29.11,Swag Se Swagat Song | Tiger Zinda Hai | Salman...,YRF,10,2017-11-21T07:03:38.000Z,"[Salman Khan, Katrina Kaif, Tiger Zinda Hai So...",40953758,679940,69161,...,False,False,False,►Watch the Tiger Zinda Hai Official Trailer: h...,IN,9.831263,07:00 - 07:10,2017,11,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100637,a3WeECF6c_U,18.05.06,WHAT HAPPENS IF YOU DROP BOWLING BALL INTO THE...,Gojzer,28,2018-05-27T08:30:40.000Z,"[shredding, bowling, ball, shredder, vs, bowli...",5846018,27321,9607,...,False,False,False,It's possible that you've already thought of w...,JP,2.843864,08:30 - 08:40,2018,6,5
135165,Q97U8K_YlOo,18.05.06,OneRepublic ft. Logic – Start Again (Audio),OneRepublic,10,2018-05-16T05:42:30.000Z,"[OneRepublic, Band, Music, Alternative, Ryan T...",7341863,110966,1677,...,False,False,False,Get ‘Start Again’ ft. Logic from the 13 Reason...,KR,66.16935,05:40 - 05:50,2018,6,5
175253,iQEVguV71sI,18.04.06,"Thalía, Natti Natasha - No Me Acuerdo (Officia...",ThaliaVEVO,10,2018-06-01T07:00:07.000Z,"[Thalia & Natti Natasha No Me Acuerdo, Thalia ...",6598933,218300,17738,...,False,False,False,Thalia & Natti Natasha – “No Me Acuerdo”NUEVO ...,MX,12.306912,07:00 - 07:10,2018,6,4
81499,i63jWjoAWHE,18.14.06,Семён Слепаков: Олé-Олé-Олé!,Семен Слепаков,23,2018-06-11T17:13:08.000Z,"[Семен Слепаков, гитара, бард-десятник, Comedy...",6597033,301192,14448,...,False,False,False,Семен в социальных сетях:FACEBOOK https://www....,RU,20.846622,17:10 - 17:20,2018,6,14
38273,7C2z4GqqS5E,18.01.06,BTS (방탄소년단) 'FAKE LOVE' Official MV,ibighit,10,2018-05-18T09:00:02.000Z,"[BIGHIT, 빅히트, 방탄소년단, BTS, BANGTAN, 방탄, FAKE LO...",123010920,5613827,206892,...,False,False,False,BTS (방탄소년단) 'FAKE LOVE' Official MVDirector : ...,US,27.134094,09:00 - 09:10,2018,6,1

## 14. Read all json files with the video categories

In [33]:
countries = [
    "US", "RU", "JP", "KR", "MX" ,"CA", "DE", "FR", "GB", "IN"
]

frames = []
for country in countries:
    json_name = 'data/' + country + "_category_id.json"
    data = pd.read_json(json_name)
    df = pd.json_normalize(data['items'])
    df["country"] = country
    frames.append(df)

categories = pd.concat(frames, ignore_index=True)
categories

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,country
0,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,US
1,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,US
2,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,US
3,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,US
4,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,US
...,...,...,...,...,...,...,...
306,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,IN
307,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,IN
308,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,IN
309,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,IN
310,youtube#videoCategory,"""XI7nbFXulYBIpL0ayR_gDh3eu1k/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,IN

## 15. For each country, determine how many videos have a category that is not assignable.

In [34]:
categories[categories['snippet.assignable'] == False].groupby('country').size()

country
CA    17
DE    17
FR    17
GB    17
IN    17
JP    17
KR    17
MX    17
RU    17
US    17
dtype: int64